const levels=[
{name:'HTML HUNT',qs:[['Which HTML element creates a hyperlink?',['<link>','<a>','<href>','<url>'],1],['Which tag creates the largest heading?',['<h6>','<head>','<h1>','<heading>'],2],['Which attribute provides alternative text for an image?',['title','src','alt','text'],2]]},
{name:'CSS FIXER',qs:[['Which CSS property changes text color?',['background','font-color','color','text-style'],2],['Which declaration makes an element a flex container?',['display: flex;','position: flex;','flex: display;','layout: flex;'],0],['Which property controls space inside an element border?',['margin','padding','spacing','gap'],1]]},
{name:'JS LOGIC',qs:[['What is the output of 2 + "2"?', ['4','22','NaN','Error'],1,'console.log(2 + "2");'],['Which keyword declares a block-scoped variable that can be reassigned?',['const','var','let','static'],2],['What does === check?',['Only value','Only type','Value and type','Variable name'],2]]},
{name:'DEBUG ZONE',qs:[['What is wrong with this code?',['Missing semicolon only','Missing closing parenthesis','Wrong variable type','Nothing'],1,'let score = 100\nconsole.log(score'],['Why is this event code incorrect?',['Wrong event name','alert is called immediately','Missing button variable','No bug'],1,"button.addEventListener('click', alert('Hi'));"],['Which line selects an element with id="game"?',['document.get("game")','document.query("#game")','document.getElementById("game")','document.id("game")'],2]]},
{name:'ALGORITHM CORE',qs:[['What should a programmer do first when solving a problem?',['Write random code','Understand the problem','Choose colors','Create a database'],1],['Which structure follows FIFO?',['Stack','Queue','Tree','Graph'],1],['Which approach repeatedly chooses the locally best option?',['Greedy','Recursive','Brute force','Random'],0]]}
];
let L=0,Q=0,score=0,lives=3,time=30,timer,correct=0,answered=0,locked=false;const $=x=>document.getElementById(x);
function screen(x){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(x).classList.add('active')}
function hud(){$('level').textContent=`${L+1}/5`;$('score').textContent=score;$('lives').textContent='❤️'.repeat(lives)+'🖤'.repeat(3-lives);$('bar').style.width=`${((L*3+Q+1)/15)*100}%`}
function start(){L=Q=score=correct=answered=0;lives=3;screen('game');load()}
function load(){clearInterval(timer);locked=false;const z=levels[L],x=z.qs[Q];$('levelName').textContent=`LEVEL ${L+1} · ${z.name}`;$('challenge').textContent=`Challenge ${Q+1}`;$('question').textContent=x[0];$('feedback').textContent='Choose an answer';$('feedback').style.color='#91a8bc';if(x[3]){$('code').textContent=x[3];$('code').classList.remove('hidden')}else $('code').classList.add('hidden');$('options').innerHTML='';x[1].forEach((v,i)=>{let b=document.createElement('button');b.className='option';b.innerHTML=`<b>${String.fromCharCode(65+i)}.</b> ${esc(v)}`;b.onclick=()=>answer(i,b);$('options').appendChild(b)});time=30;$('timer').textContent=time;hud();timer=setInterval(()=>{time--;$('timer').textContent=time;if(time<=0){clearInterval(timer);answer(-1)}},1000)}
function answer(i,clicked){if(locked)return;locked=true;clearInterval(timer);answered++;let x=levels[L].qs[Q];document.querySelectorAll('.option').forEach((b,n)=>{b.disabled=true;if(n===x[2])b.classList.add('correct')});if(i===x[2]){correct++;let pts=100+Math.min(50,time*2);score+=pts;if(clicked)clicked.classList.add('correct');$('feedback').textContent=`✓ Correct! +${pts}`;$('feedback').style.color='#43e6a1'}else{lives=Math.max(0,lives-1);if(clicked)clicked.classList.add('wrong');$('feedback').textContent=i===-1?'⌛ Time up!':'✗ Incorrect — correct answer highlighted.';$('feedback').style.color='#ff667a'}hud();setTimeout(()=>{if(!lives)return finish(false);Q++;if(Q===3){Q=0;L++;if(L===5)return finish(true)}load()},850)}
function finish(done){clearInterval(timer);screen('result');let best=Math.max(score,+localStorage.codeQuestBest||0);localStorage.codeQuestBest=best;$('final').textContent=score;$('best').textContent=best;$('accuracy').textContent=(answered?Math.round(correct/answered*100):0)+'%';$('bestStart').textContent=best;if(done){$('icon').textContent='🏆';$('resultTitle').textContent='Lab Escaped!';$('message').textContent='You cleared every challenge and unlocked the Bug Lab exit.'}else{$('icon').textContent='💥';$('resultTitle').textContent='Mission Failed';$('message').textContent='Your lives reached zero. Review the challenges and try again.'}}
$('startBtn').onclick=start;$('again').onclick=start;$('bestStart').textContent=localStorage.codeQuestBest||0;

function esc(v){return v.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));}
